CREATE SCHEMA IF NOT EXISTS db_order DEFAULT CHARACTER SET utf8;
CREATE SCHEMA IF NOT EXISTS db_inventory DEFAULT CHARACTER SET utf8;
CREATE SCHEMA IF NOT EXISTS db_payment DEFAULT CHARACTER SET utf8;
